### ISSUE TITLE
subctl join should suggest worker nodes only

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#73] opened 2019-12-01 15:40 UTC
Currently it list all cluster nodes, while user don't know which node is worker, and which is master. It should rather suggest to join the worker nodes, as suggested in Readme.

Output:

kubconf_a subctl join --clusterid subm-cluster-a ./broker-info.subm --ikeport 501 --nattport 4501
* ./broker-info.subm says broker is at: https://api.nmanos-cluster-a.devcluster.openshift.com:6443
There are 6 nodes in the cluster
? Which node should be used as the gateway?  [Use arrows to move, type to filter]
  ip-10-0-129-5.ec2.internal
  ip-10-0-136-151.ec2.internal
> ip-10-0-144-42.ec2.internal
  ip-10-0-150-183.ec2.internal
  ip-10-0-167-198.ec2.internal
  ip-10-0-173-23.ec2.internal

**Comment by skitt** [comment] 2019-12-02 08:18
This is a duplicate of #58.

**Closed by skitt** 2019-12-02 08:18 UTC
