### ISSUE TITLE
When `subctl show X` fails, it stops

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/submariner-operator#957] opened 2020-12-03 11:54 UTC
**What happened**:
Running `subctl show X` (Except `subctl show networks` which seems unaffected) when a cluster doesn't have submariner installed, causes it to fail and abort enumerating further clusters.

```shell
[root@6a37e385eb23 submariner-operator]# subctl show versions

Showing information for cluster "cluster1":
Unable to get the Submariner versions: the server could not find the requested resource (get submariners.submariner.io submariner)

subctl version: v0.8.0-rc0-1-g601ba7c
```

**What you expected to happen**:
It should fail for that cluster, but continue enumerating the other clusters.
Perhaps a different return code can be used to indicate this type of failure.

```shell
[root@6a37e385eb23 submariner-operator]# subctl show versions

Showing information for cluster "cluster1":
Unable to get the Submariner versions: the server could not find the requested resource (get submariners.submariner.io submariner)

Showing information for cluster "cluster2":
COMPONENT                       REPOSITORY                                            VERSION         
submariner                      quay.io/submariner                                    0.8.0-rc0       
submariner-operator             quay.io/submariner                                    0.8.0-rc0       
service-discovery               quay.io/submariner                                    0.8.0-rc0       

subctl version: v0.8.0-rc0
```

**How to reproduce it (as minimally and precisely as possible)**:
Deploy clusters manually according to the KIND quickstart:
```shell
make shell
make clusters
subctl deploy-broker --kubeconfig output/kubeconfigs/kind-config-cluster1 --service-discovery
subctl join --kubeconfig output/kubeconfigs/kind-config-cluster2 broker-info.subm --clusterid cluster2 --disable-nat
```

Then set KUBECONFIG so that the "broker" cluster is first:
```shell
export KUBECONFIG=/go/src/github.com/submariner-io/submariner-operator/output/kubeconfigs/kind-config-cluster1:/go/src/github.com/submariner-io/submariner-operator/output/kubeconfigs/kind-config-cluster2
```

Now any `subctl show` command (except networks) will fail on the first cluster and exit.

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`): v0.8.0-rc0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by nyechiel** [comment] 2020-12-23 07:43
Duplicate of https://github.com/submariner-io/submariner-operator/issues/958

**Closed** 2021-02-09 18:39 UTC
Labels: 0.8.0-testday, UX, bug, subctl
