### ISSUE TITLE
"make build" failed, it should be "make bin/subctl"

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#146] opened 2020-01-28 15:13 UTC
According to Operator Readme:
https://github.com/submariner-io/submariner-operator/blame/master/README.md#L14

To compile SubCTL, we should run: make build
But it failed on: `undefined: embeddedyamls.Crds_multiclusterservices_crd_yaml`
(see snippet bellow).

Running `make bin/subctl` instead - passed. So We should update Readme, or fix "make build".
```
...

Step 5/7 : RUN /usr/local/bin/user_setup
 ---> Running in 3f5fb14bd441
+ mkdir -p /root
+ chown 1001:0 /root
+ chmod ug+rwx /root
+ chmod g+rw /etc/passwd
+ rm /usr/local/bin/user_setup
 ---> 6e6083c15531
Removing intermediate container 3f5fb14bd441
Step 6/7 : ENTRYPOINT /usr/local/bin/entrypoint
 ---> Running in 4c927ce9178d
 ---> f2803b23f22b
Removing intermediate container 4c927ce9178d
Step 7/7 : USER ${USER_UID}
 ---> Running in a7b7900ff2d0
 ---> a3a14189ba8d
Removing intermediate container a7b7900ff2d0
Successfully built a3a14189ba8d
time="2020-01-26T17:40:04Z" level=info msg="Operator build complete."
[submariner-operator]$ ./scripts/generate-embeddedyamls
[submariner-operator]$ dirname ./scripts/build
[submariner-operator]$ source ./scripts/lib/version
[submariner-operator]$ dirname ./scripts/generate-embeddedyamls
[submariner-operator]$ git status --porcelain --untracked-files=no
[submariner-operator]$ COMMIT=405f7c9
[submariner-operator]$ git rev-parse --short HEAD
[submariner-operator]$ GIT_TAG=
[submariner-operator]$ git tag -l --contains HEAD
[submariner-operator]$ head -n 1
[submariner-operator]$ VERSION=dev
[submariner-operator]$ cd ./scripts/..
[submariner-operator]$ dirname ./scripts/generate-embeddedyamls
[submariner-operator]$ go generate pkg/subctl/operator/install/embeddedyamls/generate.go
Generating yamls.go
crds/submariner.io_submariners_crd.yaml
operator.yaml
role.yaml
role_binding.yaml
service_account.yaml
[submariner-operator]$ ./scripts/build-subctl
[submariner-operator]$ dirname ./scripts/build
[submariner-operator]$ source ./scripts/lib/version
[submariner-operator]$ dirname ./scripts/build-subctl
[submariner-operator]$ git status --porcelain --untracked-files=no
[submariner-operator]$ COMMIT=405f7c9
[submariner-operator]$ git rev-parse --short HEAD
[submariner-operator]$ GIT_TAG=
[submariner-operator]$ git tag -l --contains HEAD
[submariner-operator]$ head -n 1
[submariner-operator]$ VERSION=dev
[submariner-operator]$ debug=false
[submariner-operator]$ cd ./scripts/..
[submariner-operator]$ dirname ./scripts/build-subctl
[submariner-operator]$ mkdir -p bin
[submariner-operator]$ go env GOOS
[submariner-operator]$ go env GOARCH
Building subctl version dev for linux/amd64
[submariner-operator]$ GIT_COMMIT=405f7c9dbf1bda1bc1951a21a67bcd8b9b14d560
[submariner-operator]$ git rev-parse --verify HEAD^{commit}
[submariner-operator]$ ldflags=-X github.com/submariner-io/submariner-operator/pkg/version.Version=dev 
[submariner-operator]$ ldflags=-X github.com/submariner-io/submariner-operator/pkg/version.Version=dev  -X github.com/submariner-io/submariner-operator/pkg/version.Commit=405f7c9dbf1bda1bc1951a21a67bcd8b9b14d560
[submariner-operator]$ ldflags=-s -w -X github.com/submariner-io/submariner-operator/pkg/version.Version=dev  -X github.com/submariner-io/submariner-operator/pkg/version.Commit=405f7c9dbf1bda1bc1951a21a67bcd8b9b14d560
[submariner-operator]$ output=bin/subctl-dev-linux-amd64
[submariner-operator]$ CGO_ENABLED=0 go build -ldflags -s -w -X github.com/submariner-io/submariner-operator/pkg/version.Version=dev  -X github.com/submariner-io/submariner-operator/pkg/version.Commit=405f7c9dbf1bda1bc1951a21a67bcd8b9b14d560 -o bin/subctl-dev-linux-amd64 ./pkg/subctl/main.go
# github.com/submariner-io/submariner-operator/pkg/subctl/lighthouse/install/crds
pkg/subctl/lighthouse/install/crds/ensure.go:76:36: undefined: embeddedyamls.Crds_multiclusterservices_crd_yaml
note: module requires Go 1.13
[submariner-operator]$ ./scripts/build onetime false
time="2020-01-26T19:40:32+02:00" level=fatal msg="exit status 2"
make: *** [build] Error 1
```

**Comment by skitt** [comment] 2020-01-28 15:41
This is a duplicate of #126.

**Closed by skitt** 2020-01-28 15:41 UTC
