### ISSUE TITLE
OCP 4.12 + OVN-K: Basic TCP connectivity tests failed

### ISSUE THREAD

**Issue by maayanf24** [submariner-io/submariner-operator#2352] opened 2022-11-15 10:00 UTC
**What happened**:
deploy with subctl on top of OCP 4.12 clusters using 0.14.0-rc3
Some E2E tests failed, full log attached.

STEP: Verifying that the listener got the connector's data and the connector got the listener's data
STEP: Deleting namespace "e2e-tests-dataplane-conn-nd-hn8lm" on cluster "maafried-clustera1"
STEP: Deleting namespace "e2e-tests-dataplane-conn-nd-hn8lm" on cluster "maafried-cluster-b1"

• Failure [250.168 seconds]
[dataplane] Basic TCP connectivity tests across clusters without discovery
github.com/submariner-io/submariner@v0.14.0-rc3/test/e2e/dataplane/tcp_pod_connectivity.go:28
  when a pod connects via TCP to a remote pod
  github.com/submariner-io/submariner@v0.14.0-rc3/test/e2e/dataplane/tcp_pod_connectivity.go:59
    when the pod is not on a gateway and the remote pod is not on a gateway
    github.com/submariner-io/submariner@v0.14.0-rc3/test/e2e/dataplane/tcp_pod_connectivity.go:67
      should have sent the expected data from the pod to the other pod [It]
      github.com/submariner-io/submariner@v0.14.0-rc3/test/e2e/dataplane/tcp_pod_connectivity.go:36

      Expected
          <string>: listening on 0.0.0.0:1234 ...
          connect to 10.133.2.21:1234 from ip-10-128-2-22.us-east-2.compute.internal:37259 (10.128.2.22:37259)
          
      to contain substring
          <string>: 895ccda9-c27b-4903-b076-95234f28b18f

      github.com/submariner-io/shipyard@v0.14.0-rc3/test/e2e/tcp/connectivity.go:68
------------------------------
[dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote pod when the pod is not on a gateway and the remote pod is on a gateway 
  should have sent the expected data from the pod to the other pod
  github.com/submariner-io/submariner@v0.14.0-rc3/test/e2e/dataplane/tcp_pod_connectivity.go:36

**What you expected to happen**:
All `subctl verify` tests to pass

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
subctl version: v0.14.0-rc3
[submariner-0.14.0-rc3-verify-OCP-4.12.txt](https://github.com/submariner-io/submariner-operator/files/10011477/submariner-0.14.0-rc3-verify-OCP-4.12.txt)

**Environment**:
- Diagnose information (use `subctl diagnose all`): pass
- Gather information (use `subctl gather`): attached
[maafried-clustera1.tar.gz](https://github.com/submariner-io/submariner-operator/files/10011480/maafried-clustera1.tar.gz)
[maafried-cluster-b1.tar.gz](https://github.com/submariner-io/submariner-operator/files/10011484/maafried-cluster-b1.tar.gz)

- Cloud provider or hardware configuration: OCP 4.12 on AWS
- Install tools:
- Others:

**Comment by sridhargaddam** [comment] 2022-11-15 11:05
This issue is seen when using OVNKubernetes CNI in a Non-Globalnet deployment.

**Comment by yboaron** [comment] 2022-11-15 14:19
It was MTU issue, 
after applying  [1] workaround problem was fixed.

Seems like this case is similar to https://github.com/submariner-io/submariner/issues/2043 


[1] 
https://github.com/submariner-io/submariner/pull/2016

**Comment by skitt** [comment] 2022-11-15 15:04
So should we close this, or is there something that needs to be fixed so the MTU is set up correctly without user intervention?

**Comment by sridhargaddam** [comment] 2022-11-15 15:08
> So should we close this, or is there something that needs to be fixed so the MTU is set up correctly without user intervention?

Discussed with @yboaron on slack and the plan is to check if reverting this PR (https://github.com/submariner-io/submariner/pull/2016) is fixing the issue. If not, we can document the work-around (forcing MTU using annotation on GW nodes) and continue to investigate the root cause of the MTU issue.

**Comment by yboaron** [comment] 2022-11-16 10:38
> > So should we close this, or is there something that needs to be fixed so the MTU is set up correctly without user intervention?
> 
> Discussed with @yboaron on slack and the plan is to check if reverting this PR ([submariner-io/submariner#2016](https://github.com/submariner-io/submariner/pull/2016)) is fixing the issue. If not, we can document the work-around (forcing MTU using annotation on GW nodes) and continue to investigate the root cause of the MTU issue.

+1

 
I opened this [bug](https://github.com/submariner-io/submariner/issues/2132) to track MTU issues investigation.

**Comment by yboaron** [comment] 2022-11-16 13:53
I verified that e2e are green for OCP 4.12 with OVNK for v0.14.0-rc3 with customized route-agent (reverting [the relevant PR ](https://github.com/submariner-io/submariner/pull/2016)  )

**Closed as completed** 2022-11-16 19:13 UTC
Labels: bug, 0.14.0-testday
