### ISSUE TITLE
Subctl unauthorized to set the gateway node 

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#225] opened 2020-03-04 09:20 UTC
```
$ ./bin/subctl deploy-broker --service-discovery --kubecontext nmanos-cluster-a --broker-cluster-context nmanos-cluster-a --clusterid nmanos-cluster-a-tunnel --subm-debug

• Deploying broker  ...
✓ Deploying broker
• Creating broker-info.subm file  ...
✓ Creating broker-info.subm file
✓ A new IPSEC PSK will be generated for broker-info.subm
• Deploying Service Discovery controller  ...
✓ Deploying Service Discovery controller
✓ Updated existing Lighthouse entry in the openshift-dns role
✓ Updated existing Lighthouse entry in the openshift-dns-operator role
✓ Updated DNS operator deployment
✓ Restarted the DNS operator
✓ Created operator CRDs
✓ Created operator namespace: kubefed-operator
✓ Created operator service account
✓ Deployed the operator successfully
✓ Created lighthouse CRDs
✓ Created lighthouse controller

$ oc get crds | grep submariner

clusters.submariner.io                                      2020-03-03T16:00:15Z
endpoints.submariner.io                                     2020-03-03T16:00:15Z
multiclusterservices.lighthouse.submariner.io               2020-03-03T16:01:07Z

$ ./bin/subctl join --kubecontext nmanos-cluster-b --kubeconfig merged_kubeconfig --broker-cluster-context nmanos-cluster-a --clusterid nmanos-cluster-b-tunnel ./broker-info.subm --ikeport 501 --nattport 4501 --subm-debug

* ./broker-info.subm says broker is at: https://api.nmanos-cluster-a.devcluster.openshift.com:6443
Unable to set the gateway node up: Unauthorized
subctl version: dev
built from git commit id: 1a5389190d655fd0b9174a4a4f13def79bba32d9
```

[submariner_downstream_test_03032020_1755.log](https://github.com/submariner-io/submariner-operator/files/4286413/submariner_downstream_test_03032020_1755.log)

**Comment by manosnoam** [comment] 2020-03-04 14:06
Trying to switch the order of Kubconfigs in the merged_kubeconfig file, results in slightly different error, even after a clean AWS cluster setup:

Failed to get kubefed clientset: Unauthorized

```
export KUBECONFIG=/home/nmanos/automation/ocp-install/ocpup/.config/cl1/auth/kubeconfig:/home/nmanos/automation/ocp-install/nmanos-cluster-a/auth/kubeconfig
./bin/subctl join --kubecontext nmanos-cluster-b --kubeconfig merged_kubeconfig --broker-cluster-context nmanos-cluster-a --clusterid nmanos-cluster-b-tunnel ./broker-info.subm --ikeport 501 --nattport 4501 --subm-debug
* ./broker-info.subm says broker is at: https://api.nmanos-cluster-a.devcluster.openshift.com:6443
* There are 2 labeled nodes in the cluster:
  - nmanos-cl1-7jtkw-worker-46swj
  - nmanos-cl1-7jtkw-worker-wvn5d
 • Deploying the Submariner operator  ...
 ✓ Deploying the Submariner operator
 ✓ Created operator CRDs
 ✓ Created operator namespace: submariner-operator
 ✓ Created operator service account and role
 ✓ Deployed the operator successfully
 • Deploying multi cluster service discovery  ...
 ✓ Deploying multi cluster service discovery
 ✓ Updated existing Lighthouse entry in the openshift-dns role
 ✓ Updated existing Lighthouse entry in the openshift-dns-operator role
 ✓ Updated DNS operator deployment
 ✓ Restarted the DNS operator
 ✓ Created lighthouse CRDs
 • Joining to Kubefed control plane  ...
 ✗ Joining to Kubefed control plane
Error joining to Kubefed control plane: kubefedctl join failed: exit status 255
F0304 15:39:34.641747   32160 join.go:126] Error: Failed to get kubefed clientset: Unauthorized
subctl version: dev
built from git commit id: ce7f9ad7f57c6fb5790e68a4dbe60d7e597f9e3c
```

**Comment by mangelajo** [comment] 2020-03-05 10:11
@manosnoam @vthapar @aswinsuryan did we figure out why this happens ?

**Comment by aswinsuryan** [comment] 2020-03-05 10:19
@mangelajo We are yet to identify the root cause, the error is thrown by kubefedctl, since it is not able to connect to the control plane using the config we provided.

**Comment by aswinsuryan** [comment] 2020-03-05 14:53
It seems to be working when we rename the user in the config file,

$ sed -i 's/admin/west/' noam-cluster-a 
$ sed -i 's/admin/east/' noam-cluster-b
$ kubectl config view --flatten > merged_kubeconfig

$ subctl join --kubecontext nmanos-cluster-b --kubeconfig ./merged_kubeconfig --broker-cluster-context nmanos-cluster-a --clusterid nmanos-cluster-b-tunnel ./broker-info.subm --ikeport 501 --nattport 4501 --subm-debug
* ./broker-info.subm says broker is at: https://api.nmanos-cluster-a.devcluster.openshift.com:6443
* There are 2 labeled nodes in the cluster:
  - nmanos-cl1-7jtkw-worker-46swj
  - nmanos-cl1-7jtkw-worker-wvn5d
 ✓ Deploying the Submariner operator 
 ✓ Deploying multi cluster service discovery 
 ✓ Updated existing Lighthouse entry in the openshift-dns role
 ✓ Updated existing Lighthouse entry in the openshift-dns-operator role
 ✓ Updated DNS operator deployment
 ✓ Restarted the DNS operator
 ✓ Created operator namespace: kubefed-operator
 ✓ Created operator service account
 ✓ Created lighthouse CRDs
 ✓ Joining to Kubefed control plane 
* Discovering network details
    Discovered network details:
        Network plugin:  OpenShift
        Service CIDRs: [100.96.0.0/16]
        Cluster CIDRs: [10.252.0.0/14]
⢎⠁ Discovering multi cluster details     Discovered global network details for Cluster nmanos-cluster-a-tunnel:
        ServiceCidrs: [172.30.0.0/16]
        ClusterCidrs: [10.128.0.0/14]
        Global CIDRs: []
 ✓ Discovering multi cluster details
⢄⡱ Deploying Submariner * Submariner is up and running
 ✓ Deploying Submariner

**Comment by manosnoam** [comment] 2020-03-05 18:11
The root cause was having 1 user ("admin") in merged_kubeconfig, due to overriding, which have of-course wrong authentication, for the second cluster (it should have been handled by kubectl config command, to reject if there are identical usernames, for different kubeconfigs).

To workaround, it is only required to rename the user in kubeconfig of the new cluster we want to join (cluster-B).
Cluster-A user can remains as is ("admin"), and Cluster-B user is whatever (e.g. "kubfed_b").
This assures that the merged_kubeconfig includes both users:

```
$ export KUBECONFIG=/home/nmanos/automation/ocp-install/ocpup/.config/cl1/auth/kubeconfig

$ sed -i s/admin/kubefed_b/ /home/nmanos/automation/ocp-install/merged_kubeconfig_b
$ export KUBECONFIG=/home/nmanos/automation/ocp-install/nmanos-cluster-a/auth/kubeconfig:/home/nmanos/automation/ocp-install/merged_kubeconfig_b
$ oc config view --flatten > merged_kubeconfig_b
$ oc config view

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://api.nmanos-cl1.devcluster.openshift.com:6443
  name: nmanos-cl1
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://api.nmanos-cluster-a.devcluster.openshift.com:6443
  name: nmanos-cluster-a
contexts:
- context:
    cluster: nmanos-cluster-a
    user: admin
  name: nmanos-cluster-a
- context:
    cluster: nmanos-cl1
    user: kubefed_b
  name: nmanos-cluster-b
current-context: nmanos-cluster-a
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
- name: kubefed_b
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED

$ ./bin/subctl join --kubecontext nmanos-cluster-b --kubeconfig /home/nmanos/automation/ocp-install/merged_kubeconfig --broker-cluster-context nmanos-cluster-a --clusterid nmanos-cluster-b-tunnel ./broker-info.subm --ikeport 501 --nattport 4501 --subm-debug

* ./broker-info.subm says broker is at: https://api.nmanos-cluster-a.devcluster.openshift.com:6443
* There are 2 labeled nodes in the cluster:
  - nmanos-cl1-7jtkw-worker-46swj
  - nmanos-cl1-7jtkw-worker-wvn5d
 • Deploying the Submariner operator  ...
 ✓ Deploying the Submariner operator
 ✓ Created operator CRDs
 ✓ Created operator namespace: submariner-operator
 ✓ Created operator service account and role
 ✓ Deployed the operator successfully
 • Deploying multi cluster service discovery  ...
 ✓ Deploying multi cluster service discovery
 ✓ Updated existing Lighthouse entry in the openshift-dns role
 ✓ Updated existing Lighthouse entry in the openshift-dns-operator role
 ✓ Updated DNS operator deployment
 ✓ Restarted the DNS operator
 ✓ Created lighthouse CRDs
 • Joining to Kubefed control plane  ...
 ✓ Joining to Kubefed control plane
* Discovering network details
    Discovered network details:
        Network plugin:  OpenShift
        Service CIDRs: [100.96.0.0/16]
        Cluster CIDRs: [10.252.0.0/14]
 • Discovering multi cluster details  ...
 ✓ Discovering multi cluster details
 • Deploying Submariner  ...
* Submariner is up and running
 ✓ Deploying Submariner

```

**Closed** 2020-03-06 09:30 UTC
Labels: bug, lighthouse
