### ISSUE TITLE
 Issue with discovery of ClusterCIDRs on K3s

### ISSUE THREAD

**Issue by ccwalterhk** [submariner-io/submariner-operator#1730] opened 2021-12-28 13:40 UTC
**What happened**: Issue with discovery of ClusterCIDRs on K3s.  The clusterCIDRs are configured as 10.44.0.0/16 and 10.144.0.0/16.  However, when submariner does the discovery, it discover /24.

```
For Cluster A:        
    Discovered network details via Submariner:
        Network plugin:  generic
        Service CIDRs:   [10.45.0.0/16]
        Cluster CIDRs:   [10.44.0.0/24]    <---- This is the issue

For Cluster B:
    Discovered network details via Submariner:
        Network plugin:  generic
        Service CIDRs:   [10.145.0.0/16]
        Cluster CIDRs:   [10.144.0.0/24]   <---- This is the issue
```

**What you expected to happen**: Submariner should discover as /16 subnet.

**How to reproduce it (as minimally and precisely as possible)**:
Follow the exact steps in URL https://submariner.io/getting-started/quickstart/k3s/.  below is exact steps to build two clusters

```
Cluster a:
POD_CIDR=10.44.0.0/16
SERVICE_CIDR=10.45.0.0/16
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--cluster-cidr $POD_CIDR --service-cidr $SERVICE_CIDR" sh -s -

sudo snap install yq

sudo su

cp /etc/rancher/k3s/k3s.yaml kubeconfig.cluster-a
export IP=$(hostname -I | awk '{print $1}')
yq -i eval \
'.clusters[].cluster.server |= sub("127.0.0.1", env(IP)) | .contexts[].name = "cluster-a" | .current-context = "cluster-a"' \
kubeconfig.cluster-a

Cluster b:

POD_CIDR=10.144.0.0/16
SERVICE_CIDR=10.145.0.0/16
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--cluster-cidr $POD_CIDR --service-cidr $SERVICE_CIDR" sh -s -

sudo snap install yq

sudo su

cp /etc/rancher/k3s/k3s.yaml kubeconfig.cluster-b
export IP=$(hostname -I | awk '{print $1}')
yq -i eval \
'.clusters[].cluster.server |= sub("127.0.0.1", env(IP)) | .contexts[].name = "cluster-b" | .current-context = "cluster-b"' \
kubeconfig.cluster-b
```

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):

```
walter@k3-subctl-m1:~$ subctl show all --kubeconfig kubeconfig.cluster-a
Cluster "default"
 ✓ Showing Connections
GATEWAY       CLUSTER    REMOTE IP     NAT  CABLE DRIVER  SUBNETS                       STATUS     RTT avg.  
k3-subctl-w2  cluster-b  192.168.1.93  no   libreswan     10.145.0.0/16, 10.144.0.0/24  connected            

 ✓ Showing Endpoints
CLUSTER ID                    ENDPOINT IP     PUBLIC IP       CABLE DRIVER        TYPE            
cluster-a                     192.168.1.92    58.182.182.152  libreswan           local           
cluster-b                     192.168.1.93    58.182.182.152  libreswan           remote          

 ✓ Showing Gateways
NODE                            HA STATUS       SUMMARY                         
k3-subctl-w1                    active          All connections (1) are established

    Discovered network details via Submariner:
        Network plugin:  generic
        Service CIDRs:   [10.45.0.0/16]
        Cluster CIDRs:   [10.44.0.0/24]
 ✓ Showing Network details

COMPONENT                       REPOSITORY                                            VERSION         
submariner                      quay.io/submariner                                    0.11.0          
submariner-operator             quay.io/submariner                                    0.11.0          
service-discovery               quay.io/submariner                                    0.11.0          
 ✓ Showing versions

walter@k3-subctl-m1:~$ subctl show all --kubeconfig kubeconfig.cluster-b
Cluster "default"
 ✓ Showing Connections
GATEWAY       CLUSTER    REMOTE IP     NAT  CABLE DRIVER  SUBNETS                     STATUS     RTT avg.  
k3-subctl-w1  cluster-a  192.168.1.92  no   libreswan     10.45.0.0/16, 10.44.0.0/24  connected            

 ✓ Showing Endpoints
CLUSTER ID                    ENDPOINT IP     PUBLIC IP       CABLE DRIVER        TYPE            
cluster-b                     192.168.1.93    58.182.182.152  libreswan           local           
cluster-a                     192.168.1.92    58.182.182.152  libreswan           remote          

 ✓ Showing Gateways
NODE                            HA STATUS       SUMMARY                         
k3-subctl-w2                    active          All connections (1) are established

    Discovered network details via Submariner:
        Network plugin:  generic
        Service CIDRs:   [10.145.0.0/16]
        Cluster CIDRs:   [10.144.0.0/24]
 ✓ Showing Network details

COMPONENT                       REPOSITORY                                            VERSION         
submariner                      quay.io/submariner                                    0.11.0          
submariner-operator             quay.io/submariner                                    0.11.0          
service-discovery               quay.io/submariner                                    0.11.0          
 ✓ Showing versions

walter@k3-subctl-m1:~$ 
```

- Gather information (use `subctl gather`)

[submariner-cluster-B-20211227124346.tar.gz](https://github.com/submariner-io/submariner-operator/files/7784912/submariner-cluster-B-20211227124346.tar.gz)

[submariner-cluster-A-20211227124333.tar.gz](https://github.com/submariner-io/submariner-operator/files/7784913/submariner-cluster-A-20211227124333.tar.gz)

- Cloud provider or hardware configuration:
VMWARE fusion to build K3S 

- Install tools:
- Others:

**Comment by yboaron** [comment] 2022-01-27 13:31
@cwalterhk
IIUC, you used flannel as CNI, can you please confirm that?

Currently, Submariner doesn't support flannel discovery but recognizes it as a generic plugin. Though flannel cni is discovered as 'generic' plugin the routing logic should work fine.

It seems that in your case Submariner doesn't retrieve the correct pod cidr, we need more information to understand the root cause.
 
For generic plugin Submariner runs the following steps to retrieve pod cidr information :  
A. Checking for '--cluster-cidr' in the pod.Spec.Containers[i].Command for pod with  --selector=component=kube-controller-manager , see [1]

B. Checking for '--cluster-cidr' in the pod.Spec.Containers[i].Command for pod with  --selector=component=kube-proxy , see [2]

C. Loop through all nodes spec, and check for PodCIDR in node's spec

If you still can access the environment it will be useful if you can attach the output of A,B and C.


[1]
kubectl get pods --all-namespaces --selector=component=kube-controller-manager
kubectl get pods < one of the pods from first step> -o yaml | grep cluster-cidr
[2]
kubectl get pods --all-namespaces --selector=component=kube-proxy
kubectl get pods < one of the pods from forst step> -o yaml | grep cluster-cidr

**Comment by nyechiel** [comment] 2022-02-21 15:11
@yboaron are you looking at this for 0.12?

**Comment by dfarrell07** [comment] 2022-06-07 13:27
I think no one is working on this currently, if someone interested in K3s wants to pick it up that would be great.

**Comment by yboaron** [comment] 2022-06-09 09:02
I'm not working on it, I have a PR [1] that expands our cni discovery logging, it should help us understand the root cause of bugs related to generic cnis discovery.


[1] https://github.com/submariner-io/submariner-operator/pull/1833

**Comment by yboaron** [comment] 2023-03-19 10:40
Several fixes [1] related to CNI Flannel detection were pushed in recent Submariner releases. @ccwalterhk , if it's still relevant,  you can try it using the latest Submariner release. 

[1]
https://github.com/submariner-io/submariner-operator/pull/2451
https://github.com/submariner-io/submariner-operator/pull/1850

**Comment by dfarrell07** [comment] 2023-08-22 13:21
Looks like there have been some relevant fixes. Closing this for now, feel free to re-open if it's still an issue.

**Closed as completed by dfarrell07** 2023-08-22 13:21 UTC
Labels: bug, help wanted, K3s
