### ISSUE TITLE
Multiple repetitive errors in the operator

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-operator#1111] opened 2021-02-25 11:15 UTC
**What happened**:

In the operator logs:

```

2021-02-25T11:14:11.395Z	ERROR	controller-runtime.controller	Reconciler error	{"controller": "broker", "name": "submariner-broker", "namespace": "submariner-operator", "error": "error provisioning the Cluster CRD: no kind is registered for the type v1.CustomResourceDefinition in scheme \"github.com/submariner-io/submariner-operator/main.go:72\""}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/go-logr/zapr/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/src/github.com/submariner-io/submariner-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:248
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/src/github.com/submariner-io/submariner-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:222
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/src/github.com/submariner-io/submariner-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:201
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/go/src/github.com/submariner-io/submariner-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/src/github.com/submariner-io/submariner-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/go/src/github.com/submariner-io/submariner-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88

```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tpantelis** [comment] 2021-04-07 21:54
Where was this seen and has it recently been reproduced?

**Comment by tpantelis** [comment] 2021-04-07 23:22
_no kind is registered for the type v1.CustomResourceDefinition_ is a client-side issue - it means the CRD type in `apiextensions` wasn't registered with the scheme we create in `main.go`:

```
var (
	scheme = apiruntime.NewScheme()
)
```

However we do statically register the schema here:

```
func init() {
	...
	utilruntime.Must(apiextensions.AddToScheme(scheme))
}
```

This was added about 5 weeks ago by https://github.com/submariner-io/submariner-operator/pull/1122 so this issue has since been fixed. As such I'm closing this issue.

**Closed as completed** 2021-04-07 23:25 UTC
Labels: bug
