### ISSUE TITLE
Please add subctl cleanup/unjoin option

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#88] opened 2019-12-09 14:59 UTC
This is useful for Testing or other scenarios, where the user would like to remove Submariner engine and Operator.

notes by @mangelajo:

   - this should cleanup the related endpoints
   - this should cleanup the CableEngine tunnels on the deployment (this needs to be signaled to the submariner-gateway somehow, and be waited for).

**Comment by manosnoam** [comment] 2019-12-17 12:35
@skitt, just want to let you know that deleting the namespace is not enough, you also need to delete crds:

```
$ kubconf_b  oc delete namespace submariner-operator
namespace "submariner-operator" deleted

$ kubconf_b  oc get crds -n submariner-operator
NAME                                                        CREATED AT
alertmanagers.monitoring.coreos.com                         2019-12-05T19:57:21Z
apiservers.config.openshift.io                              2019-12-05T19:50:00Z
authentications.config.openshift.io                         2019-12-05T19:50:01Z
authentications.operator.openshift.io                       2019-12-05T19:50:33Z
baremetalhosts.metal3.io                                    2019-12-05T19:53:16Z
builds.config.openshift.io                                  2019-12-05T19:50:01Z
catalogsourceconfigs.operators.coreos.com                   2019-12-05T19:50:30Z
catalogsources.operators.coreos.com                         2019-12-05T19:50:38Z
clusterautoscalers.autoscaling.openshift.io                 2019-12-05T19:50:31Z
clusternetworks.network.openshift.io                        2019-12-05T19:50:44Z
clusteroperators.config.openshift.io                        2019-12-05T19:49:59Z
clusterresourcequotas.quota.openshift.io                    2019-12-05T19:50:00Z
clusters.submariner.io                                      2019-12-05T20:25:39Z
clusterserviceversions.operators.coreos.com                 2019-12-05T19:50:37Z
clusterversions.config.openshift.io                         2019-12-05T19:49:59Z
configs.imageregistry.operator.openshift.io                 2019-12-05T19:50:30Z
configs.samples.operator.openshift.io                       2019-12-05T19:50:29Z
consoleclidownloads.console.openshift.io                    2019-12-05T19:50:30Z
consoleexternalloglinks.console.openshift.io                2019-12-05T19:50:34Z
consolelinks.console.openshift.io                           2019-12-05T19:50:32Z
consolenotifications.console.openshift.io                   2019-12-05T19:50:35Z
consoles.config.openshift.io                                2019-12-05T19:50:01Z
consoles.operator.openshift.io                              2019-12-05T19:50:36Z
containerruntimeconfigs.machineconfiguration.openshift.io   2019-12-05T19:52:40Z
controllerconfigs.machineconfiguration.openshift.io         2019-12-05T19:52:37Z
credentialsrequests.cloudcredential.openshift.io            2019-12-05T19:50:31Z
dnses.config.openshift.io                                   2019-12-05T19:50:01Z
dnses.operator.openshift.io                                 2019-12-05T19:50:30Z
dnsrecords.ingress.operator.openshift.io                    2019-12-05T19:50:31Z
egressnetworkpolicies.network.openshift.io                  2019-12-05T19:50:45Z
endpoints.submariner.io                                     2019-12-05T20:25:39Z
featuregates.config.openshift.io                            2019-12-05T19:50:01Z
hostsubnets.network.openshift.io                            2019-12-05T19:50:44Z
imagecontentsourcepolicies.operator.openshift.io            2019-12-05T19:50:02Z
images.config.openshift.io                                  2019-12-05T19:50:02Z
infrastructures.config.openshift.io                         2019-12-05T19:50:02Z
ingresscontrollers.operator.openshift.io                    2019-12-05T19:50:33Z
ingresses.config.openshift.io                               2019-12-05T19:50:02Z
installplans.operators.coreos.com                           2019-12-05T19:50:38Z
kubeapiservers.operator.openshift.io                        2019-12-05T19:50:31Z
kubecontrollermanagers.operator.openshift.io                2019-12-05T19:50:30Z
kubeletconfigs.machineconfiguration.openshift.io            2019-12-05T19:52:39Z
kubeschedulers.operator.openshift.io                        2019-12-05T19:50:31Z
machineautoscalers.autoscaling.openshift.io                 2019-12-05T19:50:33Z
machineconfigpools.machineconfiguration.openshift.io        2019-12-05T19:52:38Z
machineconfigs.machineconfiguration.openshift.io            2019-12-05T19:52:36Z
machinedisruptionbudgets.healthchecking.openshift.io        2019-12-05T19:51:05Z
machinehealthchecks.healthchecking.openshift.io             2019-12-05T19:51:05Z
machines.machine.openshift.io                               2019-12-05T19:51:04Z
machinesets.machine.openshift.io                            2019-12-05T19:51:04Z
mcoconfigs.machineconfiguration.openshift.io                2019-12-05T19:50:35Z
netnamespaces.network.openshift.io                          2019-12-05T19:50:44Z
network-attachment-definitions.k8s.cni.cncf.io              2019-12-05T19:50:40Z
networks.config.openshift.io                                2019-12-05T19:50:02Z
networks.operator.openshift.io                              2019-12-05T19:50:04Z
oauths.config.openshift.io                                  2019-12-05T19:50:03Z
openshiftapiservers.operator.openshift.io                   2019-12-05T19:50:31Z
openshiftcontrollermanagers.operator.openshift.io           2019-12-05T19:50:32Z
operatorgroups.operators.coreos.com                         2019-12-05T19:50:39Z
operatorhubs.config.openshift.io                            2019-12-05T19:50:00Z
operatorsources.operators.coreos.com                        2019-12-05T19:50:32Z
podmonitors.monitoring.coreos.com                           2019-12-05T19:57:21Z
projects.config.openshift.io                                2019-12-05T19:50:03Z
prometheuses.monitoring.coreos.com                          2019-12-05T19:57:21Z
prometheusrules.monitoring.coreos.com                       2019-12-05T19:57:21Z
proxies.config.openshift.io                                 2019-12-05T19:50:00Z
rolebindingrestrictions.authorization.openshift.io          2019-12-05T19:49:59Z
schedulers.config.openshift.io                              2019-12-05T19:50:03Z
securitycontextconstraints.security.openshift.io            2019-12-05T19:50:00Z
servicecas.operator.openshift.io                            2019-12-05T19:50:32Z
servicecatalogapiservers.operator.openshift.io              2019-12-05T19:50:31Z
servicecatalogcontrollermanagers.operator.openshift.io      2019-12-05T19:50:31Z
servicemonitors.monitoring.coreos.com                       2019-12-05T19:57:21Z
submariners.submariner.io                                   2019-12-05T20:25:22Z
subscriptions.operators.coreos.com                          2019-12-05T19:50:38Z
tuneds.tuned.openshift.io                                   2019-12-05T19:50:31Z
```

**Comment by skitt** [comment] 2019-12-17 12:40
> @skitt, just want to let you know that deleting the namespace is not enough, you also need to delete crds:

If you do this, you’ll destroy your cluster. `kubectl get crds -n submariner-operator` shows all CRDs, because CRDs aren’t in a namespace, therefore the `-n submariner-operator` option has no effect.

**Comment by manosnoam** [comment] 2019-12-17 13:20
Not sure if CRDs is the only non-namespaced resources, which is part of submariner, that should be deleted with the cleanup.

To list all resources outside namespaces:
$ oc api-resources --namespaced=false

**Comment by mangelajo** [comment] 2020-02-05 09:26
@tpantelis unassigned you since I see you busy in other topics just to make sure others are aware about this being a item that can use some hands.

**Comment by sridhargaddam** [comment] 2020-05-11 12:26
As part of cleanup we should also cleanup the following
1. IPTable rules programmed on the worker nodes by Submariner
2. Routing rules on the nodes that were programmed to route inter-cluster traffic.
3. IPsec tunnels

**Comment by Tarjei400** [comment] 2020-06-22 07:17
Is there a finite list of steps where one can do a manual cleanup? That would be really helpful as now I am not sure if reinstalling submariner doesnt interfere with previous settings. Thanks for any advices!

**Comment by sridhargaddam** [comment] 2020-06-22 08:15
@Tarjei400 Hey,

Until, this issue is addressed, you can manually run the following commands to cleanup Submariner.

**On all the data/member clusters**
kubectl delete namespace submariner-operator

If you are using vanilla Submariner, please delete the following iptable chains from the nat/filter table of worker nodes
SUBMARINER-INPUT
SUBMARINER-POSTROUTING

The following chains will have to be deleted if you are using Globalnet.
SUBMARINER-GN-INGRESS
SUBMARINER-GN-EGRESS
SUBMARINER-GN-MARK

Also, its recommended that you delete the vx-submariner interface from all the nodes.

**On the Broker cluster**
kubectl delete namespace submariner-k8s-broker

**Comment by manosnoam** [comment] 2020-06-24 11:28
What about "submariner-operator" namespace, shouldn't we delete it as well ?

**Comment by sridhargaddam** [comment] 2020-06-24 11:39
> What about "submariner-operator" namespace, shouldn't we delete it as well ?

If you have a dedicated broker node, it will not have the "submariner-operator" namespace. But if you use the cluster for both Broker as well as data cluster, you will see "submariner-operator". So, yes if you use the cluster as Broker+Data cluster you will have to delete both the namespaces.

In the instructions I shared earlier, I included the following.
**On all the data/member clusters**
kubectl delete namespace submariner-operator

**Comment by skitt** [comment] 2020-09-30 10:43
This would still be useful.

**Comment by sridhargaddam** [comment] 2020-11-29 14:38
bump

**Comment by nyechiel** [comment] 2021-01-24 14:54
Duplicate of https://github.com/submariner-io/submariner-operator/issues/1039

**Closed by nyechiel** 2021-01-24 14:54 UTC
Labels: UX, enhancement, help wanted
