### ISSUE TITLE
`subctl benchmark throughput` not working with globalnet on kind (non-gw to non-gw)

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/submariner-operator#1488] opened 2021-07-15 07:26 UTC
**What happened**:
Running the command with globalnet env on kind, getting this (gw-to-gw truncated for brevity):
```bash
[root@483221d9c954 submariner]# subctl benchmark throughput --kubecontexts cluster1,cluster2
Performing throughput tests from Gateway pod on cluster "cluster1" to Gateway pod on cluster "cluster2"
its/sec  169   40.1 KBytes       
...
[ 23]   7.00-8.00   sec  11.4 MBytes  96.1 Mbits/sec  191   33.6 KBytes       
[SUM]   7.00-8.00   sec   124 MBytes  1.04 Gbits/sec  1772             
- - - - - - - - - - - - - - - - - - - - - - - - -
...
[ 23]   8.00-9.00   sec  11.4 MBytes  95.5 Mbits/sec  229   44.0 KBytes       
[SUM]   8.00-9.00   sec   123 MBytes  1.03 Gbits/sec  1656             
- - - - - - - - - - - - - - - - - - - - - - - - -
...
[ 23]   9.00-10.00  sec  12.0 MBytes   101 Mbits/sec  172   31.0 KBytes       
[SUM]   9.00-10.00  sec   125 MBytes  1.05 Gbits/sec  2097             
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
...
[ 23]   0.00-10.01  sec   109 MBytes  91.3 Mbits/sec                  receiver
[SUM]   0.00-10.00  sec  1.19 GBytes  1.02 Gbits/sec  17471             sender
[SUM]   0.00-10.01  sec  1.18 GBytes  1.02 Gbits/sec                  receiver

iperf Done.

Performing throughput tests from Non-Gateway pod on cluster "cluster1" to Non-Gateway pod on cluster "cluster2"
iperf3: error - unable to connect to server: Operation timed out
[going to retry]
iperf3: error - unable to connect to server: Operation timed out
[going to retry]
```

**What you expected to happen**:
Should also run for non-gw to non-gw

**How to reproduce it (as minimally and precisely as possible)**:
```bash
make deploy using=globalnet
subctl benchmark throughput --kubecontexts cluster1,cluster2
```

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`): v0.10.0-rc0
- Kubernetes version (use `kubectl version`): v1.20.7
- Diagnose information (use `subctl diagnose all`): All pass
- Gather information (use `subctl gather`) 
[gather.tar.gz](https://github.com/submariner-io/submariner-operator/files/6821176/gather.tar.gz)

- Cloud provider or hardware configuration: Kind
- OS (e.g `cat /etc/os-release`): F34
- Kernel (e.g `uname -a`):
- Install tools:
- Others:

**Comment by mkolesnik** [comment] 2021-07-15 08:01
This is also affecting `subctl verify` obviously.

[verify.txt](https://github.com/submariner-io/submariner-operator/files/6821365/verify.txt)

**Comment by sridhargaddam** [comment] 2021-07-15 17:40
I'm not able to reproduce this issue locally after creating KIND Clusters (using `make clusters`) and deploying Submariner with subctl-0.10.rc0 release image.

Looking at the globalnet pod logs, I don't see any errors that could potentially cause this failure. However, I noticed in the logs the time difference between the service creation and service deletion is on an average of 20 to 25 seconds. Ideally, this should be fine, but just to rule out the timing issue, if we reproduce this issue once again, we can retry `subctl verify` increasing the --connection-attempts and --connection-timeout once.

```
I0715 07:08:12.728547       1 global_ingressip_controller.go:123] Processing created &v1.GlobalIngressIP{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"test-svc-nettest-server-pod", GenerateName:"", Namespace:"e2e-tests-throughput-5g22k", SelfLink:"", UID:"aa780592-fa0f-4f74-8b6d-9d5826b37de4", ResourceVersion:"2779", Generation:1, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63761929692, loc:(*time.Location)(0x2021f00)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"submariner-io/originatingNamespace":"e2e-tests-throughput-5g22k"}, Annotations:map[string]string{"submariner.io/kubeproxy-iptablechain":"KUBE-SVC-67SUIWKZQ3VYIS7H"}, OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry{v1.ManagedFieldsEntry{Manager:"submariner-globalnet", Operation:"Update", APIVersion:"submariner.io/v1", Time:(*v1.Time)(0xc0010de900), FieldsType:"FieldsV1", FieldsV1:(*v1.FieldsV1)(0xc0010de918)}}}, Spec:v1.GlobalIngressIPSpec{Target:"ClusterIPService", ServiceRef:(*v1.LocalObjectReference)(0xc001195630), PodRef:(*v1.LocalObjectReference)(nil)}, Status:v1.GlobalIngressIPStatus{Conditions:[]v1.Condition(nil), AllocatedIP:""}}
I0715 07:08:12.728600       1 global_ingressip_controller.go:146] Allocating global IP for "e2e-tests-throughput-5g22k/test-svc-nettest-server-pod"
I0715 07:08:12.728630       1 iface.go:113] Installing iptables rule for Service -d 242.1.255.252 -j KUBE-SVC-67SUIWKZQ3VYIS7H
I0715 07:08:12.732997       1 global_egressip_controller.go:309] Updated: &v1.GlobalIngressIPStatus{Conditions:[]v1.Condition{v1.Condition{Type:"Allocated", Status:"True", ObservedGeneration:0, LastTransitionTime:v1.Time{Time:time.Time{wall:0xc03415972bb074d4, ext:203202928734, loc:(*time.Location)(0x2021f00)}}, Reason:"Success", Message:"Allocated global IP"}}, AllocatedIP:"242.1.255.252"}
I0715 07:08:32.596151       1 service_controller.go:111] Service "e2e-tests-throughput-5g22k/test-svc-nettest-server-pod" deleted
I0715 07:08:32.653785       1 service_export_controller.go:184] ServiceExport "e2e-tests-throughput-5g22k/test-svc-nettest-server-pod" deleted
I0715 07:08:32.661804       1 global_ingressip_controller.go:123] Processing deleted &v1.GlobalIngressIP{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"test-svc-nettest-server-pod", GenerateName:"", Namespace:"e2e-tests-throughput-5g22k", SelfLink:"", UID:"aa780592-fa0f-4f74-8b6d-9d5826b37de4", ResourceVersion:"2850", Generation:2, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63761929692, loc:(*time.Location)(0x2021f00)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"submariner-io/originatingNamespace":"e2e-tests-throughput-5g22k"}, Annotations:map[string]string{"submariner.io/kubeproxy-iptablechain":"KUBE-SVC-67SUIWKZQ3VYIS7H"}, OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry{v1.ManagedFieldsEntry{Manager:"submariner-globalnet", Operation:"Update", APIVersion:"submariner.io/v1", Time:(*v1.Time)(0xc00000c5e8), FieldsType:"FieldsV1", FieldsV1:(*v1.FieldsV1)(0xc00000c600)}}}, Spec:v1.GlobalIngressIPSpec{Target:"ClusterIPService", ServiceRef:(*v1.LocalObjectReference)(0xc0006ea990), PodRef:(*v1.LocalObjectReference)(nil)}, Status:v1.GlobalIngressIPStatus{Conditions:[]v1.Condition{v1.Condition{Type:"Allocated", Status:"True", ObservedGeneration:0, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63761929692, loc:(*time.Location)(0x2021f00)}}, Reason:"Success", Message:"Allocated global IP"}}, AllocatedIP:"242.1.255.252"}}
I0715 07:08:32.661918       1 base_controllers.go:151] Releasing previously allocated IPs [242.1.255.252] for "e2e-tests-throughput-5g22k/test-svc-nettest-server-pod"
I0715 07:08:32.661941       1 iface.go:129] Deleting iptable ingress rule for Service: -d 242.1.255.252 -j KUBE-SVC-67SUIWKZQ3VYIS7H
```

**Comment by mkolesnik** [comment] 2021-07-19 09:02
Quite strange, when it happened it seemed consistent (e.g the broken state remained even after a few minutes to stabilize), but I've also tried to reproduce it from scratch and was unable to get it again.

Seems the problem is non-deterministic so the only clues are in these logs from `subctl gather`.

**Comment by sridhargaddam** [comment] 2021-11-10 15:53
As this is not reproducible in the latest builds, closing this for now. We can reopen/open-a-new-one if required.

**Closed as completed by sridhargaddam** 2021-11-10 15:53 UTC
Labels: bug, size:small, priority:low, 0.10.0-testday
