### ISSUE TITLE
The operator should handle the broker

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#98] opened 2019-12-17 14:05 UTC
We need to move this from `subctl` to the operator.

**Comment by mangelajo** [comment] 2020-06-15 13:09
This is a dupe of https://github.com/submariner-io/submariner-operator/issues/203

**Closed by mangelajo** 2020-06-15 13:09 UTC
Labels: operator

**Comment by skitt** [comment] 2020-06-15 13:46
> This is a dupe of #203

Technically, #203 is a dupe of this ;-).
