### ISSUE TITLE
Node Selector for Pods Created by Custom Resources

### ISSUE THREAD

**Issue by tunahanertekin** [submariner-io/submariner-operator#2434] opened 2023-01-02 14:11 UTC
Hi there, 

Is there a way to assign node selectors for pods which are created by custom resources like `Submariner` or `ServiceDiscovery`? I was able to add node selector to deployment `submariner-operator` by adding a new value `nodeSelector` to Helm `values.yaml`, but **couldn't find a way to schedule other pods to a desired node**.

Thanks.

**Comment by dfarrell07** [comment] 2023-01-03 14:18
Hello! Thanks for the question! These are relevant:
https://github.com/submariner-io/enhancements/issues/149
https://github.com/submariner-io/submariner-operator/issues/2362

I think this is a duplicate of #2362. If you have more discussion let's include it there.

**Closed as completed** 2023-01-03 14:20 UTC
