### ISSUE TITLE
OCP 4.12: failed to run `subctl diagnose firewall inter-cluster`

### ISSUE THREAD

**Issue by maayanf24** [submariner-io/submariner-operator#2332] opened 2022-11-07 13:44 UTC
**What happened**:
running `subctl diagnose firewall inter-cluster` failed:
```
subctl diagnose firewall inter-cluster --context cluster-b1 --remotecontext cluster-a1
 ✗ Checking if tunnels can be setup on the gateway node of cluster "maafried-cluster-b1" 
 ✗ Error: the gateway on cluster "maafried-cluster-a1" does not have an active connection to cluster "maafried-cluster-b1"
 ✗ Error retrieving the gateway IP of cluster "maafried-cluster-b1": Error: the gateway on cluster "maafried-cluster-a1" does not have an active connection to cluster "maafried-cluster-b1"
 ✗ Could not determine if Tunnels can be established on the gateway node of cluster "maafried-cluster-b1"

subctl version: v0.14.0-rc2
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
OCP 4.12 on AWS,
submariner 0.14.0-rc2
[maafried-cluster-a1.tar.gz](https://github.com/submariner-io/submariner-operator/files/9952107/maafried-cluster-a1.tar.gz)
[maafried-cluster-b1.tar.gz](https://github.com/submariner-io/submariner-operator/files/9952109/maafried-cluster-b1.tar.gz)

- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by nyechiel** [comment] 2022-11-07 13:49
This is likely not specific to OCP 4.12, but to the 0.14 kubeconfig handling changes.

**Comment by skitt** [comment] 2022-11-07 17:21
This happens because the context names don’t match the cluster names. The contexts are named `cluster-a1` and `cluster-b1`, but the clusters are named `maayan-cluster-a1` and `maayan-cluster-b1`. The clusters ended up joined using the context names rather than the cluster names, and then `diagnose firewall inter-cluster` looks for connections matching the cluster names and fails (because they list the context names).

`subctl` should be fixed so that cluster names should be used consistently — they are the only stable reference.

**Comment by Jaanki** [comment] 2022-11-09 10:53
I could reproduce this on KIND setup as well. To reproduce, `join` the clusters with `--clusterid` arguments.

**Closed as completed** 2022-11-11 05:50 UTC
Labels: bug, 0.14.0-testday

**Comment by Jaanki** [comment] 2022-11-11 06:30
Backport on 0.14: https://github.com/submariner-io/subctl/pull/373
