### ISSUE TITLE
--subm-debug cannot be used as first argument to subctl 

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#340] opened 2020-04-28 06:13 UTC
```
subctl --subm-debug join --kubecontext nmanos-cluster-b --kubeconfig /mnt/skynet-data/ocp-install/merged_kubeconfig --clusterid nmanos-cluster-b-tunnel ./broker-info.subm --ikeport 501 --nattport 4501
Error: unknown command "./broker-info.subm" for "subctl"
```

**Comment by sridhargaddam** [comment] 2020-04-28 06:26
If you look at the subctl usage, it clearly says that the first argument should be the command (and not arguments). So, IMO this is not a bug. If you pass "--subm-debug anywhere after the join" command, it works fine.

Usage:
 subctl [command]
Available Commands:
 deploy-broker      set the broker up
 help               Help about any command
 info               Get information on your cluster related to submariner
 join               connect a cluster to an existing broker
 verify-connectivity Verify connectivity between two clusters
 version            Get version information on subctl

**Comment by manosnoam** [comment] 2020-04-28 09:08
I changed it this to an enhancement request.
--subm-debug should be a global flag to subctl commands, when using "join", "deploy-broker" or any other option, just like kubectl has -v flag for verbosity.

**Comment by mangelajo** [comment] 2020-04-28 12:15
It should not be a global flag, because it's deploy/join specific, the other commands are not affected by that flag (info , verify-connectivity) etc... it's deployment detail only.

**Comment by mangelajo** [comment] 2020-05-05 14:26
@manosnoam I will close this because the framework we use for cmdline processing does not let us do that.

**Closed by mangelajo** 2020-05-05 14:26 UTC
Labels: enhancement
